name: Build PyQt6 EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyqt6 faker selenium pyperclip

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed cursorautoreg.py
          
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: cursorautoreg-exe
          path: dist/cursorautoreg.exe
