name: Build EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build with PyInstaller
        run: pyinstaller --onefile --windowed cursorautoreg.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cursorautoreg-exe
          path: dist/cursorautoreg.exe
